services:
  ap-pos:
    image: marcogll/ap_pos:1.3.5
    container_name: ap-pos
    restart: unless-stopped
    ports:
      - "3111:3111"
    environment:
      NODE_ENV: production
      SESSION_SECRET: ${SESSION_SECRET:-your-very-secret-key-change-it-in-production}
      DB_PATH: /app/data/ap-pos.db
    volumes:
      - ./data:/app/data
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3111/login.html"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

# volumes section no longer needed - using direct bind mount
